---
title: "day3_lab"
output: html_document
date: "2026-06-25"
---

```{r}

sanfran = read.csv("sanfran.csv")
x = ts(sanfran,start = c(1932,1),end = c(1966,12),frequency = 12)
x_train = window(x,end = c(1964,12))
x_test = window(x, start = c(1965,1))



plot(x_train, col = "blue", lwd = 2,
     xlim = range(time(x)),
     ylim = range(x),
     xlab = "Time", ylab = "Value",
     main = "Train vs Test Time Series")

lines(x_test, col = "red", lwd = 2)

abline(v = start(x_test), lty = 2)

legend("topleft",
       legend = c("Train", "Test"),
       col = c("blue", "red"),
       lwd = 2
       )
```

```{r}
acf(x)
```
```{r}
pacf(x)
```
```{r}
add_seasonal = HoltWinters(x_train,alpha = NULL,beta = NULL,gamma = NULL)
add_seasonal_pred = predict(add_seasonal,n.ahead=length(x_test), prediction.interval = TRUE)



plot(x_train, col = "blue", lwd = 2,
     xlim = range(time(x)),
     ylim = range(c(x_train, x_test, add_seasonal_pred[,1])),
     xlab = "Time", ylab = "Value",
     main = "Train vs Test vs Prediction")

lines(x_test, col = "red", lwd = 2)

lines(add_seasonal_pred[,'fit'], col = "darkgreen", lwd = 2)

abline(v = start(x_test), lty = 2)

legend("topleft",
       legend = c("Train", "Test", "Forecast"),
       col = c("blue", "red", "darkgreen"),
       lwd = 2)
```
```{r}
accuracy(add_seasonal_pred,x_test)
```

