---
title: "Time Series CV CO2"
output:
  pdf_document: default
  html_document:
    df_print: paged
date: "2026-06-24"
---

```{r}
library(forecast)
x = co2
# split the last one year for testing 
test= window(x,start=c(1997,1))
train = window(x,end = c(1996,12))
autoplot(train, series="Train")+
  autolayer(test,series = "Test")
```

# Cross validation to compare different model

```{r}
mape = function(forecast,truth){
  return (100*mean(abs(truth-forecast)/truth))
}
#initialize datafram to store cv result of models 
cv_results = data.frame(
  Model = character(),
  Fold = integer(),
  MAPE = numeric(),
  stringsAsFactors = FALSE

)

start_year = start(train)[1]
end_year = end(train)[1]

for (i in (start_year+1):(end_year[1]-1)){
  # the first train fold has 24 observations
  train_fold = window(train,end = c(i,12))
  # the validation fold has 12 observation 
  val_fold = window(train,start=c(i+1,1),end = c(i+1,12))
  

  #Simple exponential smoothing
  ses = HoltWinters(train_fold,alpha = NULL,beta = FALSE, gamma=FALSE)
  ses_pred = predict(ses,n.ahead=length(val_fold),)
  cv_results = rbind( 
                cv_results,
                data.frame(
                  Model = "SES",
                  Fold = i,
                  MAPE = mape(ses_pred[,"fit"],val_fold)
                )
                )
  # non seasonal exponential smooth
  non_seasonal = HoltWinters(train_fold,alpha = NULL,beta = NULL,gamma = FALSE)
  non_seasonal_pred = predict(non_seasonal,n.ahead=length(val_fold))
  cv_results = rbind( 
                cv_results,
                data.frame(
                  Model = "non_seasonal",
                  Fold = i,
                  MAPE = mape(non_seasonal_pred[,"fit"],val_fold)
                )
                )
  #additive seasonal exponential smoothing 
  add_seasonal = HoltWinters(train_fold,alpha = NULL,beta = NULL,gamma = NULL)
  add_seasonal_pred = predict(add_seasonal,n.ahead=length(val_fold))
  cv_results = rbind( 
                cv_results,
                data.frame(
                  Model = "add_seasonal",
                  Fold = i,
                  MAPE = mape(add_seasonal_pred[,"fit"],val_fold)
                )
                )
  #multiplicative seasonal 
  multi_seasonal = HoltWinters(train_fold,alpha = NULL,beta = NULL,gamma = NULL, seasonal = "multi")
  multi_seasonal_pred = predict(multi_seasonal,n.ahead=length(val_fold))
  cv_results = rbind( 
              cv_results,
              data.frame(
                Model = "multi_seasonal",
                Fold = i,
                MAPE = mape(multi_seasonal_pred[,"fit"],val_fold)
              )
              )

}


summary_results <- do.call(
  data.frame,
  aggregate(
    MAPE ~ Model,
    data = cv_results,
    FUN = function(x)
      c(
        Mean_MAPE = mean(x, na.rm = TRUE),
        SD_MAPE   = sd(x, na.rm = TRUE)
      )
  )
)

print(summary_results)
```
```{r}
# train the best model with the full trianing set 
best_model = HoltWinters(train,alpha = NULL,beta = NULL,gamma = NULL, seasonal = "multi")
# test on the left out dataset
best_forecast = predict(best_model,n.ahead=length(test))
mape(best_forecast[,"fit"],test)
```


```{r}
autoplot(train, series="Train")+
  autolayer(test,series = "Test")+
  autolayer(best_forecast,series = "Forecast")
```


